-- Les documents de démonstration ne sont plus insérés automatiquement.
-- Les exemples (analyses de sol, certificats fictifs, etc.) créaient l’impression
-- de données réelles dans l’app. Ajoutez vos documents via l’écran Documents (+).
